### PR TITLE
Enable subnetwork specification

### PR DESCRIPTION
**Pull request by junpayment**
Enable subnetwork specification.

I attempted to specify subnetwork for terraform.tfvars, but because it was set to overwrite subnetwork with network, it was an error if the network name and subnetwork name were different.

```
subnetwork = "${var.network}"
```

Added variable of subnetwork.

### CODE REVIEW

**Comment by junpayment** [comment]
I signed it!

**Comment by danisla** [comment]
Can you make the default value of the subnetwork variable `“”` and the argument default to the value of `var.network` if not provided? That makes the change backwards compatible. 

Also, can you update the HA GKE example too?

**Comment by junpayment** [comment]
@danisla I fixed it.

**Comment by danisla** [comment]
Great, LGTM, thank you!

**Pull request merged**
