### PR TITLE
Add name variable for resource prefixes. Import of multi network example.

### LINKED ISSUE #13: Allow multiple NAT instances in the same zone
Our project has the following structure:

- 4 networks: mgmt, int, stg, prd
- 2 subnetworks for each network: us-east1-c, us-west1-a

When trying to create NAT instances, the following error is reported from terraform:

```
* module.mgmt-nat-us-west-1-a.module.nat-gateway.google_compute_firewall.default-ssh: 1 error(s) occurred:

* google_compute_firewall.default-ssh: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-west1-a-vm-ssh' already exists, alreadyExists
* module.stg-nat-us-west-1-a.module.nat-gateway.google_compute_health_check.mig-health-check: 1 error(s) occurred:

* google_compute_health_check.mig-health-check: Error creating HealthCheck: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/healthChecks/nat-gateway-us-west1-a' already exists, alreadyExists
* module.mgmt-nat-us-west-1-a.google_compute_firewall.nat-gateway: 1 error(s) occurred:

* google_compute_firewall.nat-gateway: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-us-west1-a' already exists, alreadyExists
* module.prd-nat-us-east-1-c.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.int-nat-us-west-1-a.module.nat-gateway.google_compute_firewall.mig-health-check: 1 error(s) occurred:

* google_compute_firewall.mig-health-check: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-west1-a-vm-hc' already exists, alreadyExists
* module.stg-nat-us-west-1-a.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.mgmt-nat-us-east-1-c.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.int-nat-us-west-1-a.module.nat-gateway.google_compute_firewall.default-ssh: 1 error(s) occurred:

* google_compute_firewall.default-ssh: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-west1-a-vm-ssh' already exists, alreadyExists
* module.prd-nat-us-west-1-a.module.nat-gateway.google_compute_firewall.default-ssh: 1 error(s) occurred:

* google_compute_firewall.default-ssh: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-west1-a-vm-ssh' already exists, alreadyExists
* module.mgmt-nat-us-west-1-a.module.nat-gateway.google_compute_health_check.mig-health-check: 1 error(s) occurred:

* google_compute_health_check.mig-health-check: Error creating HealthCheck: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/healthChecks/nat-gateway-us-west1-a' already exists, alreadyExists
* module.int-nat-us-west-1-a.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.prd-nat-us-east-1-c.module.nat-gateway.google_compute_firewall.default-ssh: 1 error(s) occurred:

* google_compute_firewall.default-ssh: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-east1-c-vm-ssh' already exists, alreadyExists
* module.mgmt-nat-us-east-1-c.module.nat-gateway.google_compute_firewall.mig-health-check: 1 error(s) occurred:

* google_compute_firewall.mig-health-check: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-east1-c-vm-hc' already exists, alreadyExists
* module.mgmt-nat-us-west-1-a.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.int-nat-us-east-1-c.google_compute_firewall.nat-gateway: 1 error(s) occurred:

* google_compute_firewall.nat-gateway: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-us-east1-c' already exists, alreadyExists
* module.int-nat-us-east-1-c.module.nat-gateway.google_compute_firewall.mig-health-check: 1 error(s) occurred:

* google_compute_firewall.mig-health-check: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-east1-c-vm-hc' already exists, alreadyExists
* module.int-nat-us-west-1-a.google_compute_firewall.nat-gateway: 1 error(s) occurred:

* google_compute_firewall.nat-gateway: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-us-west1-a' already exists, alreadyExists
* module.prd-nat-us-west-1-a.module.nat-gateway.google_compute_health_check.mig-health-check: 1 error(s) occurred:

* google_compute_health_check.mig-health-check: Error creating HealthCheck: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/healthChecks/nat-gateway-us-west1-a' already exists, alreadyExists
* module.prd-nat-us-west-1-a.google_compute_firewall.nat-gateway: 1 error(s) occurred:

* google_compute_firewall.nat-gateway: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-us-west1-a' already exists, alreadyExists
* module.int-nat-us-east-1-c.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.mgmt-nat-us-west-1-a.module.nat-gateway.google_compute_firewall.mig-health-check: 1 error(s) occurred:

* google_compute_firewall.mig-health-check: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-west1-a-vm-hc' already exists, alreadyExists
* module.mgmt-nat-us-east-1-c.module.nat-gateway.google_compute_firewall.default-ssh: 1 error(s) occurred:

* google_compute_firewall.default-ssh: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-east1-c-vm-ssh' already exists, alreadyExists
* module.prd-nat-us-west-1-a.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.stg-nat-us-east-1-c.module.nat-gateway.google_compute_health_check.mig-health-check: 1 error(s) occurred:

* google_compute_health_check.mig-health-check: Error creating HealthCheck: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/healthChecks/nat-gateway-us-east1-c' already exists, alreadyExists
* module.prd-nat-us-east-1-c.google_compute_firewall.nat-gateway: 1 error(s) occurred:

* google_compute_firewall.nat-gateway: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-us-east1-c' already exists, alreadyExists
* module.stg-nat-us-east-1-c.google_compute_address.default: 1 error(s) occurred:

* google_compute_address.default: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
* module.mgmt-nat-us-east-1-c.google_compute_firewall.nat-gateway: 1 error(s) occurred:

* google_compute_firewall.nat-gateway: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-us-east1-c' already exists, alreadyExists
* module.prd-nat-us-east-1-c.module.nat-gateway.google_compute_firewall.mig-health-check: 1 error(s) occurred:

* google_compute_firewall.mig-health-check: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-east1-c-vm-hc' already exists, alreadyExists
* module.mgmt-nat-us-east-1-c.module.nat-gateway.google_compute_health_check.mig-health-check: 1 error(s) occurred:

* google_compute_health_check.mig-health-check: Error creating HealthCheck: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/healthChecks/nat-gateway-us-east1-c' already exists, alreadyExists
* module.int-nat-us-east-1-c.module.nat-gateway.google_compute_firewall.default-ssh: 1 error(s) occurred:

* google_compute_firewall.default-ssh: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-east1-c-vm-ssh' already exists, alreadyExists
* module.int-nat-us-east-1-c.module.nat-gateway.google_compute_health_check.mig-health-check: 1 error(s) occurred:

* google_compute_health_check.mig-health-check: Error creating HealthCheck: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/healthChecks/nat-gateway-us-east1-c' already exists, alreadyExists
* module.prd-nat-us-west-1-a.module.nat-gateway.google_compute_firewall.mig-health-check: 1 error(s) occurred:

* google_compute_firewall.mig-health-check: Error creating firewall: googleapi: Error 409: The resource 'projects/<<project-redacted>>/global/firewalls/nat-gateway-us-west1-a-vm-hc' already exists, alreadyExists
```

It seems that the zone is used as a name in different places, making it non-unique across different networks. I'd be happy to contribute a patch 😃

### PR DESCRIPTION
**Pull request by danisla**
Fixes #13 

- Added `name` input variable. This is prefixed to unique resources in the module. This change is backwards-compatible.
- Added `examples/multiple-nat-environments` example showing how to create NAT gateway instances in multiple networks.

### CODE REVIEW

**Comment by danisla** [comment]
@vinceprignano, LMK if this works for your scenario.

**Comment by vinceprignano** [comment]
Looks good! I'll try it out later today and report back

**Comment by vinceprignano** [comment]
@danisla can this be merged? this looks fine to me

**Comment by danisla** [comment]
@vinceprignano indeed, thanks for checking it out!

**Pull request merged**
