### PR TITLE
Adds labelling to the underlying gateway instances.

### PR DESCRIPTION
**Pull request by prodriguezdefino**
Adds a variable for instance labels now that the MIG module supports labels on its Instance Templates.

### CODE REVIEW

**Comment by danisla** [comment]
@prodriguezdefino I want to merge your changes. 
I was trying to rebase your branch and somehow closed the PR on accident. Can you re-push the commit to reopen this PR?

**Comment by danisla** [comment]
Also, I have your change on my branch here: https://github.com/danisla/terraform-google-nat-gateway/tree/add-instance-labels

In general, it's easier to merge changes if you do them on a branch rather than on your master.

I can just merge my branch if you want as well.

**Comment by prodriguezdefino** [comment]
just merge your branch, thanks for adding this!

**Comment by danisla** [comment]
No problem, thanks so much for the contribution!

**Pull request closed without merging**
